Some notes on developing the 35t GeGeDe model.

* The =larsoft= builders

The 35t builders are in the =lbne.geo.builders.thirtyfive= module.  This namespace attempts to predict the future layout of an LBNE Python module hierarchy and as such may seem deeper than strictly needed at this point.

The =.larsoft= module provides builders suitable for creating a geometry that matches the limitations and requirements that LArSoft imposes on the geometry it is able to consume.  It also is meant to match the organization of the "v2" 35t geometry (links below).  It tries to exploit the symmetries of the geometry:

 - long (L) vs. short (S) TPC dimensions in X
 - small (S) vs. medium (M) vs. large (L) dimensions in Y
 - identical dimensions in Z

Some words on each builder, from coarse to fine detail:

** Cryostat

The =larsoft.Cryostat= builder produces a box holding the TPCs.  It is configured with a "gap" and an "offset" in each of the X, Y and Z directions which are used to position each of the 8 TPCs volumes.  It assumes several things about its sub-builders that will product each TPC volume:

 - They are named like: =TPC_[SML][SL]= in the config file
 - They provide a "=.hdim=" tuple holding (dx,dy,dz) half dimensions of the TPC volume

** TPC 

The =larsoft.TPC= builder provides the =.hdim= required by =larsoft.Cryostat=.  It contains a set of global defaults of dimensions and then based on its own name it will determine it's x,y,z (full) dimensions.  These can be overridden on a case-by-case basis in the configuration file if desired (eg, to check on variations from nominal).  The Z dimension is taken to be the same between all TPCs as assumed by =larsoft.Cryostat=.

* Other descriptions

 - [[https://cdcvs.fnal.gov/redmine/projects/lbnecode/wiki/LBNE_Geometries#35t-Prototype-Geometry][lbnecode wiki]] has a figure with some major elements labeled and with a "global" coordinate system definition. See also [[https://cdcvs.fnal.gov/redmine/projects/35ton/wiki/Lbne35t4apa_v3][v3]] for 35t geo from Tyler.  

   - [[https://cdcvs.fnal.gov/redmine/projects/lbnecode/repository/revisions/develop/entry/lbne/Geometry/gdml/lbne35t4apa_v2_nowires.gdml][lbne35t4apa_v2_nowires]] in git repo

   - [[https://github.com/WCSim/WCSim/blob/develop/src/WCSimConstructMaterials.cc][WCSim materials]]

 - [[https://github.com/czczc/LArViewer/tree/master/LBNE35t/Geometry][Chao's display]] has a GDML and a ROOT file with some geometry, presumably dumped from LArSoft(?)

 - [[http://lbne2-docdb.fnal.gov:8080/cgi-bin/ShowDocument?docid=7550][35t parameters]] gives a spread sheet with various dimensions and other parameters and includes a page with some 3D model renderings

 - [[http://lbne2-docdb.fnal.gov:8080/cgi-bin/ShowDocument?docid=6642][Alan Hahn 2012]] collaboration report has photos of concrete exterior, steel vapor barrier, foam insulation, SS membrane, top exterior 

 - [[https://sharepoint.fnal.gov/project/lbne/reviews/35t%20Phase%202%20Detector%20Testing%20and%20Assembly%20Review/SitePages/Agenda.aspx][35t Phase 2 Detector Testing and Assembly Review]] [2014-06-16]

    - [[http://lbne2-docdb.fnal.gov:8080/cgi-bin/ShowDocument?docid=9181][Photon Detectors]]  Page 3 numbering convention, pages 5-7 construction details, 

 - [[https://sharepoint.fnal.gov/project/lbne/35t%20Phase%202%20Detector%20Installation%20Readiness%20Review/SitePages/Agenda.aspx][35t Phase 2 Detector Installation Readiness Review]] [2014-08-25]

   - [[http://lbne2-docdb.fnal.gov:8080/cgi-bin/ShowDocument?docid=9588][35t overview]] 

   - [[http://lbne2-docdb.fnal.gov:8080/cgi-bin/ShowDocument?docid=9176][Field Cage Design]] only has the 0.006" thickness dimension

* Requirements to match LArSoft

After a phone convo with Tyler and eyeballing =lbne35t4apa_v2*.gdml=:

** Naming conventions

LArSoft requires specifically named parts for major detector elements matching pattern: =volXxx=:

 - =volCryostat=
 - =volTPC=
 - ...

** Coordinate conventions

They originate from novasoft -> nutools -> larsoft -> lbnecode.  Z in the nominal beam direction, X parallel to drift and such that major volume is all positive with the minor volume and wire planes being negative.  Y to follow to provide right hand coordinate system.

